export const NAKSHATRA_DATA = [
  {
    name: 'Ashwini',
    symbol: 'Horse Head',
    lord: 'Ketu',
    deity: 'Ashwini Kumaras',
    nature: 'Swift/Healing',
    startDegree: 0,
  },
  {
    name: 'Bharani',
    symbol: 'Yoni',
    lord: 'Venus',
    deity: 'Yama',
    nature: 'Creative/Transformative',
    startDegree: 13.333,
  },
  {
    name: 'Krittika',
    symbol: 'Razor',
    lord: 'Sun',
    deity: 'Agni',
    nature: 'Purifying/Fierce',
    startDegree: 26.667,
  },
  {
    name: 'Rohini',
    symbol: 'Chariot',
    lord: 'Moon',
    deity: 'Brahma',
    nature: 'Fertile/Indulgent',
    startDegree: 40,
  },
  {
    name: 'Mrigashira',
    symbol: 'Deer Head',
    lord: 'Mars',
    deity: 'Soma',
    nature: 'Searching/Curious',
    startDegree: 53.333,
  },
  {
    name: 'Ardra',
    symbol: 'Teardrop',
    lord: 'Rahu',
    deity: 'Rudra',
    nature: 'Intense/Transformative',
    startDegree: 66.667,
  },
  {
    name: 'Punarvasu',
    symbol: 'Bow and Arrow',
    lord: 'Jupiter',
    deity: 'Aditi',
    nature: 'Renewing/Optimistic',
    startDegree: 80,
  },
  {
    name: 'Pushya',
    symbol: 'Lotus',
    lord: 'Saturn',
    deity: 'Brihaspati',
    nature: 'Nourishing/Spiritual',
    startDegree: 93.333,
  },
  {
    name: 'Ashlesha',
    symbol: 'Serpent',
    lord: 'Mercury',
    deity: 'Naga',
    nature: 'Mystical/Intuitive',
    startDegree: 106.667,
  },
  {
    name: 'Magha',
    symbol: 'Throne',
    lord: 'Ketu',
    deity: 'Pitrs',
    nature: 'Royal/Ancestral',
    startDegree: 120,
  },
  {
    name: 'Purva Phalguni',
    symbol: 'Hammock',
    lord: 'Venus',
    deity: 'Bhaga',
    nature: 'Pleasurable/Creative',
    startDegree: 133.333,
  },
  {
    name: 'Uttara Phalguni',
    symbol: 'Bed',
    lord: 'Sun',
    deity: 'Aryaman',
    nature: 'Patronage/Friendly',
    startDegree: 146.667,
  },
  {
    name: 'Hasta',
    symbol: 'Hand',
    lord: 'Moon',
    deity: 'Savitar',
    nature: 'Skillful/Healing',
    startDegree: 160,
  },
  {
    name: 'Chitra',
    symbol: 'Jewel',
    lord: 'Mars',
    deity: 'Vishvakarma',
    nature: 'Artistic/Bright',
    startDegree: 173.333,
  },
  {
    name: 'Swati',
    symbol: 'Coral',
    lord: 'Rahu',
    deity: 'Vayu',
    nature: 'Independent/Liberal',
    startDegree: 186.667,
  },
  {
    name: 'Vishakha',
    symbol: 'Archway',
    lord: 'Jupiter',
    deity: 'Indra-Agni',
    nature: 'Determined/Goal-oriented',
    startDegree: 200,
  },
  {
    name: 'Anuradha',
    symbol: 'Lotus',
    lord: 'Saturn',
    deity: 'Mitra',
    nature: 'Devoted/Friendship',
    startDegree: 213.333,
  },
  {
    name: 'Jyeshtha',
    symbol: 'Circular Talisman',
    lord: 'Mercury',
    deity: 'Indra',
    nature: 'Senior/Protective',
    startDegree: 226.667,
  },
  {
    name: 'Mula',
    symbol: 'Tied Bunch',
    lord: 'Ketu',
    deity: 'Nirrti',
    nature: 'Investigative/Spiritual',
    startDegree: 240,
  },
  {
    name: 'Purva Ashadha',
    symbol: 'Tusk',
    lord: 'Venus',
    deity: 'Apas',
    nature: 'Invincible/Flowing',
    startDegree: 253.333,
  },
  {
    name: 'Uttara Ashadha',
    symbol: 'Elephant Tusk',
    lord: 'Sun',
    deity: 'Vishvadevas',
    nature: 'Victorious/Universal',
    startDegree: 266.667,
  },
  {
    name: 'Shravana',
    symbol: 'Ear',
    lord: 'Moon',
    deity: 'Vishnu',
    nature: 'Listening/Knowledgeable',
    startDegree: 280,
  },
  {
    name: 'Dhanishta',
    symbol: 'Drum',
    lord: 'Mars',
    deity: 'Vasus',
    nature: 'Wealthy/Musical',
    startDegree: 293.333,
  },
  {
    name: 'Shatabhisha',
    symbol: 'Circle',
    lord: 'Rahu',
    deity: 'Varuna',
    nature: 'Healing/Mysterious',
    startDegree: 306.667,
  },
  {
    name: 'Purva Bhadrapada',
    symbol: 'Sword',
    lord: 'Jupiter',
    deity: 'Aja Ekapada',
    nature: 'Intense/Spiritual',
    startDegree: 320,
  },
  {
    name: 'Uttara Bhadrapada',
    symbol: 'Twin',
    lord: 'Saturn',
    deity: 'Ahir Budhnya',
    nature: 'Deep/Profound',
    startDegree: 333.333,
  },
  {
    name: 'Revati',
    symbol: 'Fish',
    lord: 'Mercury',
    deity: 'Pushan',
    nature: 'Journeying/Nourishing',
    startDegree: 346.667,
  },
] as const;

export type NakshatraData = (typeof NAKSHATRA_DATA)[number];
